name: Security Audit

on:
  schedule:
    # Run weekly on Mondays at 9:00 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual triggering

jobs:
  security-audit:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run npm audit
      id: audit
      run: |
        npm audit --json > audit-results.json || true
        VULNERABILITIES=$(cat audit-results.json | jq '.metadata.vulnerabilities.total // 0')
        echo "vulnerabilities=$VULNERABILITIES" >> $GITHUB_OUTPUT
        
        if [ "$VULNERABILITIES" -gt 0 ]; then
          echo "Found $VULNERABILITIES vulnerabilities"
          npm audit --audit-level moderate
          exit 1
        else
          echo "No vulnerabilities found"
        fi
    
    - name: Create Issue on Security Vulnerabilities
      if: failure() && steps.audit.outputs.vulnerabilities > 0
      uses: actions/github-script@v7
      with:
        script: |
          const title = `Security Alert: ${context.payload.steps?.audit?.outputs?.vulnerabilities || 'Unknown'} vulnerabilities found`;
          const body = `
          ## 🚨 Security Vulnerabilities Detected
          
          Our weekly security audit has detected vulnerabilities in the project dependencies.
          
          **Number of vulnerabilities:** ${context.payload.steps?.audit?.outputs?.vulnerabilities || 'Unknown'}
          
          ### Action Required
          Please review and fix these vulnerabilities by running:
          \`\`\`bash
          npm audit
          npm audit fix
          \`\`\`
          
          ### Automated Weekly Check
          This issue was created automatically by our weekly security audit workflow.
          
          ---
          *Last checked: ${new Date().toISOString()}*
          `;
          
          // Check if there's already an open security issue
          const issues = await github.rest.issues.listForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'open',
            labels: 'security'
          });
          
          const existingIssue = issues.data.find(issue => 
            issue.title.includes('Security Alert')
          );
          
          if (existingIssue) {
            // Update existing issue
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: existingIssue.number,
              body: `## 🔄 Security Update\n\n${body}`
            });
          } else {
            // Create new issue
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: body,
              labels: ['security', 'priority-high']
            });
          }